### PR TITLE
Studentbrad/scrape speed

### LINKED ISSUE #18: Scraping glassdoor is too slow
Perhaps we should default the configuration to a shallower scrape?

### PR DESCRIPTION
**Pull request by studentbrad**
Implemented multithreading to improve scrape speed.
Surprisingly this improves speed on Linux and Windows.

fixes #18

### CODE REVIEW

**Comment by itSeez** [comment]
why does pycharm need to call `python run.py`? can't it just do `funnel -s settings.yaml`?

**Comment by studentbrad** [comment]
@itSeez I tried that too.  The reason why is because Pycharm insists on calling `python` first.  If you run the debugger, because pycharm uses a python script for debugging it must call `python <debug script> <your script>`.

**Comment by studentbrad** [comment]
I'm stupid.  I didn't realize pycharm had a `module` option for exactly this reason.
image
I removed run.py and updated the pycharm document.

**Comment by itSeez** [comment]
don't forget the version number :P

**Pull request merged**
