### PR TITLE
Create python-publish.yml

### PR DESCRIPTION
**Pull request by markkvdb**
# Publish package to PyPi

## Description

Installating jobfunnel is done using the GitHub url but this would allow the package to also be installed from the PyPi distribution.

## Context of change

Please add options that are relevant and mark any boxes that apply.

- [ ] Software (software that runs on the PC)
- [x] Library (library that runs on the PC)
- [ ] Tool (tool that assists coding development)
- [ ] Other

## Type of change

Please mark any boxes that apply.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## How Has This Been Tested?

Most important thing is to check if package successfully uploads to test-pypi.

## Checklist:

Please mark any boxes that have been completed.

- [x] I have performed a self-review of my own code.
- [ ] I have commented my code, particularly in hard-to-understand areas.
- [ ] I have made corresponding changes to the documentation.
- [x] My changes generate no new warnings.
- [ ] I have added tests that prove my fix is effective or that my feature works.
- [ ] New and existing unit tests pass locally with my changes.
- [ ] Any dependent changes have been merged and published in downstream modules.

### CODE REVIEW

**Comment by markkvdb** [comment]
@PaulMcInnis to add jobfunnel to PyPi we need to provide the login credentials. I made an account that we can use but since you're the owner of the repo, you have to add the credentials to the secrets.

**Comment by markkvdb** [comment]
PyPi seems to work. Only issue seems to be showing images from the README on the PyPi homepage. @PaulMcInnis if you could send me your PyPi account then I'll add you to the repository as an owner. You should add these credentials as secrets using the names as specified in python-publish.yml.

**Comment by markkvdb** [comment]
Did you create an account yet? @PaulMcInnis

**Comment by PaulMcInnis** [comment]
> Did you create an account yet? @PaulMcInnis

Sorry out of town for a few days. Will get to this asap!

**Comment by markkvdb** [comment]
> > Did you create an account yet? @PaulMcInnis
> 
> Sorry out of town for a few days. Will get to this asap!

No worries. Enjoy!

**Review by PaulMcInnis — APPROVED** [review]
Looks good! Glad to see this wasn't too complicated. 

I've got an account created under `paulmcinnis99`

**Comment by markkvdb** [comment]
Added your account. Hope all will go well once we merge this pull in the master ...

**Comment by PaulMcInnis** [comment]
> Added your account. Hope all will go well once we merge this pull in the master ...

cool, will it push the latest release?

**Comment by markkvdb** [comment]
You first have to save your password and username as secrets in the repository. After, when you create a release in Github, it will run the python-publish.yml file. Hopefully resulting in an update on PyPi.

**Comment by PaulMcInnis** [comment]
Awesome OK, Let me create a task for myself to implement this, thanks for updating the code to support it!

**Pull request merged**
