### PR TITLE
Generated Pipfile.lock from setup.py - Reverted setup.py

### LINKED ISSUE #26: pip installer is broken
pip installer fails to install because it can't find `pipenv`.

Currently none of the installation instructions on the readme work.

### PR DESCRIPTION
**Pull request by studentbrad**
I have no clue how else to solve this issue.  I guess the creators of pipenv didn't really think about how this parsing function assumes the user already has pipenv installed.

I posted the question on stackoverflow because I honestly have no idea.
https://stackoverflow.com/questions/57104559/what-if-setup-py-has-dependencies

fixes #26

### CODE REVIEW

**Comment by studentbrad** [comment]
I see what I did wrong here.  I should have reviewed my last pull request more before merging.  Pipfile was only ever intended for applications.  However Pipfile.lock can also be generated from setup.py.  I should have been using setup.py to generate Pipfile.lock and not vice-versa.  I will make this correction.  Sorry about that.

**Comment by itSeez** [comment]
If the pipfile.lock is generated now, then shouldn't git ignore it?

**Comment by itSeez** [comment]
don't forget to bump the version number.

**Comment by studentbrad** [comment]
@itSeez Pipfile.lock is less recommended to be committed for libraries.
More-so for applications.  I have no opinions on it.

**Pull request merged**
