### PR TITLE
[indeed] better page result parsing

### PR DESCRIPTION
**Pull request by Maddin-619**
This PR checks if there are no results so the None exception is avoided.
With germen domain the page result string is 'Seite 1 von 189 Jobs' and the r'f (\d+) ' regex dose not match. I tought that it should be better for international support to prevent language dependent regex.

### CODE REVIEW

**Comment by PaulMcInnis** [comment]
Apologies - we merged some fixes recently - looks like there is a minor conflict now.

**Comment by studentbrad** [comment]
Something weird happened to this PR.  The merge didn't occur as I would expect.  Though changes have been made since, we should only see your changes and not others.  The number of commits dilutes the actual changes and therefore I cannot review them properly :disappointed:.

**Comment by Maddin-619** [comment]
I rebased my feature branch onto the master branch to resolve the conflicts. For review you can just look at my last commit. Basically it is just another regex for page parsing. Merge should be work fine, not my commits will be ignored. Maybe you can squash commits. Sorry next time I will better use merge.

**Comment by studentbrad** [comment]
Could be too risky merging these changes for the reason stated above.
This has happened to me a few times before.

What I have done in the past is merged master with my branch.
Next, I used Kdiff3 to find my actual changes including files and lines.
Finally, I copied the files with changes to a new branch, forked from master, effectively only showing my actual changes.

**Pull request closed without merging**
