### PR TITLE
upgraded requirements and setup for python 3.9

### PR DESCRIPTION
**Pull request by rambalachandran**
# Pull Request Template

## Description

Please include a summary of the change.
Please also include relevant motivation and context.
List any additional libraries that will be affected.
List any developers that will be affected or those who you had merge conflicts with.

## Context of change

Please add options that are relevant and mark any boxes that apply.

- [ ] Software (software that runs on the PC)
- [ ] Library (library that runs on the PC)
- [ ] Tool (tool that assists coding development)
- [ ] Other

## Type of change

Please mark any boxes that apply.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## How Has This Been Tested?

Please describe the tests that you ran to verify your changes.
Provide instructions so we can reproduce.
Please also list any relevant details for your test configuration.

- [ ] Test A
- [ ] Test B

## Checklist:

Please mark any boxes that have been completed.

- [ ] I have performed a self-review of my own code.
- [ ] I have commented my code, particularly in hard-to-understand areas.
- [ ] I have made corresponding changes to the documentation.
- [ ] My changes generate no new warnings.
- [ ] I have added tests that prove my fix is effective or that my feature works.
- [ ] New and existing unit tests pass locally with my changes.
- [ ] Any dependent changes have been merged and published in downstream modules.

### CODE REVIEW

**Comment by thebigG** [comment]
Hey @rambalachandran, thanks for the update!

I'm curious: is JobFunnel working on your end?

**Comment by rambalachandran** [comment]
@thebigG No not working at this time. I'm also getting the error mentioned in Issue #144. Can you please let me know if there is an old commit when it was working that I can revert to and upgrade the requirements and test.

**Comment by PaulMcInnis** [comment]
Unfortunately this project has been more or less killed by that issue, until someone with some interest can help us out. Captcha has effectively broken our cli tool.

**Comment by thebigG** [comment]
Just like @PaulMcInnis said: CAPTCHA and dynamically-loaded sites have unfortunately rendered this project useless. It is unfortunate, but the CAPTCHA is something we just simply cannot solve by just writing code. If they want to give us a CAPTCHA, they will give us CAPTCHA. There isn't much we can do about it. 

I tried getting around it, but couldn't really figure anything out. If anyone is interested in what I was working on(which I'm not anymore), you can look here:https://github.com/thebigG/JobFunnel/tree/dynamic_scraping

If anyone wants to give it a go, go ahead by all means. But honestly I'm not sure if this issue can really be solved in code. Though I hope I'm wrong about that.

**Comment by PaulMcInnis** [comment]
Seems our pipeline isn't getting any runners... hmm.

**Comment by PaulMcInnis** [comment]
Closing this until we resolve #148

**Pull request closed without merging**
