### PR TITLE
Travis CI: Use flake8 to find undefined names

### PR DESCRIPTION
**Pull request by cclauss**
Add flake8 to Travis CI to find undefined names: https://flake8.pycqa.org/en/latest/user/error-codes.html

On the flake8 test selection, this PR does not focus on "style violations" (the majority of flake8 error codes that psf/black can autocorrect). Instead these tests are focus on runtime safety and correctness:

* E9 tests are about Python syntax errors usually raised because flake8 can not build an Abstract Syntax Tree (AST). Often these issues are a sign of unused code or code that has not been ported to Python 3. These would be compile-time errors in a compiled language but in a dynamic language like Python they result in the script halting/crashing on the user.
* F63 tests are usually about the confusion between identity and equality in Python. Use ==/!= to compare str, bytes, and int literals is the classic case. These are areas where a == b is True but a is b is False (or vice versa). Python >= 3.8 will raise SyntaxWarnings on these instances.
* F7 tests logic errors and syntax errors in type hints
* F82 tests are almost always undefined names which are usually a sign of a typo, missing imports, or code that has not been ported to Python 3. These also would be compile-time errors in a compiled language but in Python a NameError is raised which will halt/crash the script on the user.

### CODE REVIEW

**Comment by cclauss** [comment]
https://travis-ci.com/PaulMcInnis/JobFunnel/builds/143221276#L213

**Comment by PaulMcInnis** [comment]
Sounds good, if I’m understanding this correctly we will need to make some formatting and style improvements to pass the build with these changes right?

Additonally, can you please rebase onto v2.0?

**Comment by cclauss** [comment]
this PR does not focus on "style violations"

**Comment by PaulMcInnis** [comment]
Erm right. 

Ok. Seems like the build is passing now.

**Comment by studentbrad** [comment]
Can we merge this now?  I see no issues.

**Pull request merged**
